Проект готов к защите
htmlacademy-adaptive/28451-cat-energy-22 pull request #1
Opened 2021-05-06 10:33 UTC by Junfrontend

2021-05-10 13:11 UTC, wrgraff requested changes
Так. Проверял-проверял, не закончил. Накопилось большое количество правок.
Именно по объему.

1. Нужно поправить структуру файлов. Для этого придется перелопатить все стили, поэтому я решил, что не буду сейчас детально их смотреть, так как потом не найду что и где поменялось. Поэтому давай разберемся с этим сперва.
  Про это внутри тоже указал.
2. Почему-то вокруг сайта есть какие-то серые поля. Серых полей быть не должно, фон должен тянуться от края до края на любом разрешении. Это само собой разумеется, но даже специально [в ТЗ указано](https://up.htmlacademy.ru/adaptive/22/project/cat-energy#cat-energy-3-2)

Вот это тебе 2 основные больше задачи. И пара мелких в ревью.
Надо сделать и тогда уже смотреть будем дальше

2021-05-14 21:44 UTC, wrgraff requested changes
По пиксель перфекту довольно много несоответствий нашел, описал их [в файле](https://paper.dropbox.com/doc/28451--BKtkJAhHDetbC2fxJH0HCPI5AQ-g3hH8oYdlMsJR7fg8vPNI)

Все файлы, где я нашел селекторы других блоков, пересматривай полностью, я не комментировал каждый селектор.

2021-05-14 21:44 UTC, wrgraff commented on source/index.html
> +          <input class="toggle-wrapper__toggle-button" type="checkbox">
Такие вещи реализуются с помощью js. Не нужно делать их через инпуты.
Например, в данном случае инпут никак не поможет реализации большой картинки на планшете. А должен, поскольку это тот же самый блок интерфейса.

2021-05-14 21:44 UTC, wrgraff commented on source/catalog.html
> +        <a href="#"><img class="card__image" src="img/chiken_500_1x.png" srcset="img/chiken_500_2x.png 2x"  alt="Картинка товара" width="68" height="87"></a>
По критерию [Б20](https://up.htmlacademy.ru/adaptive/22/criteries#b20) нужно кадрировать все картинки каталога.
Вообще, по доп критериям там будет еще и другое кадрирование, но для защиты нужно кадрировать хотя бы эти

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/purpose.less
> +}
Псевдоэлементы в чекбоксах не работают в Firefox.
А по критерию [Б27](https://up.htmlacademy.ru/adaptive/22/criteries#b27) все должно быть идентично.
Такая реализация у тебя по сути везде. Нужно переделать на более кроссбраузерную.

2021-05-14 21:44 UTC, wrgraff commented on source/less/global.less
> +    width: 1440px;
Ты не можешь ограничивать ширину всей странице.
У тебя должны [тянуться фоны и другие элементы, которые упираются в края страницы, на всю ширину](https://up.htmlacademy.ru/adaptive/22/project/cat-energy#cat-energy-3-2).

2021-05-14 21:44 UTC, wrgraff commented on source/catalog.html
> +    <a>
Логотип на внутренних страницах [должен ссылаться на главную](https://up.htmlacademy.ru/adaptive/22/project/cat-energy#cat-energy-3-3) (на странице формы тоже)

2021-05-14 21:44 UTC, wrgraff commented on source/catalog.html
> +      <a class="links-wrapper__logo"><img src="img/text-logo.svg" alt="Картинка с лого" height="24" width="128"></a>
Лого и в футере тоже должно быть ссылкой

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/header.less
> +  }
[Без использования js эта кнопка должна быть скрыта](https://up.htmlacademy.ru/adaptive/22/project/cat-energy#cat-energy-3-6).
У тебя если скрипт отключить, кнопка закрытия меню все равно остается.

2021-05-14 21:44 UTC, wrgraff commented on source/js/script.js
> +}
Помимо самого механизма скрытия/открытия меню еще должно быть закрыто после того, как JS инициализируется

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/intro-program.less
> +    box-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);
А откуда тень взялась?
На этой и других кнопках. В стайлгайде такого нет

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/slimming-and-weight-gain.less
> +      transform: translate(10px) scaleX(1.5);
Не подходит такая реализация. Так стрелка растягивается, а у нее должен удлиняться только "черенок"

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/toggle-wrapper.less
> +    }
Так при нажатии текст смещается.
Нужно найти другой способ, чтобы они оставались на месте

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/about-cat.less
> +      outline: 2px solid @spicial-grey-middle;
Откуда взялась рамка 2 пикселя при наведении?
2 пикселя рамка там только при фокусе:
![изображение](https://user-images.githubusercontent.com/37917037/118334339-0bfd7500-b516-11eb-8622-c42f5c96a1ba.png)

Кстати, а где состояние фокуса?

2021-05-14 21:44 UTC, wrgraff commented on source/less/blocks/owner-contacts.less
> +  }
На вашем потоке в макете была ошибка.
Разумеется, состояние с черной рамкой и цветной иконкой — это фокус, а не disabled:

![изображение](https://user-images.githubusercontent.com/37917037/118334638-a52c8b80-b516-11eb-8ecd-7845d0d98f7f.png)

2021-05-20 14:22 UTC, Junfrontend commented on source/index.html
> +          <img class="before-and-after__img" src="img/cat_before_program1x.png" alt="Картинка кота до программы"
Насколько я помню, реализация котов остается на усмотрение ученика, так что я пока не хочу их реализовывать. И так много где косячу

2021-05-20 14:23 UTC, Junfrontend commented on source/index.html
> +          <input class="toggle-wrapper__toggle-button" type="checkbox">
У меня через этот инпут реализована смена картинок котов в мобильной версии

2021-05-20 14:26 UTC, Junfrontend commented on source/index.html
> +          <input class="toggle-wrapper__toggle-button" type="checkbox">
Но я переделал уже

2021-05-20 21:45 UTC, wrgraff commented on source/index.html
> +          <input class="toggle-wrapper__toggle-button" type="checkbox">
Я как раз написал почему реализация через чекбокс здесь не к месту

2021-05-20 22:11 UTC, wrgraff commented on source/index.html
> +          <img class="before-and-after__img" src="img/cat_before_program1x.png" alt="Картинка кота до программы"
Если ты про пункт [4.4](https://up.htmlacademy.ru/adaptive/22/project/cat-energy#cat-energy-4-4):

> В блоке «Живой пример» слайдер реализовывать необязательно. Достаточно вёрстки, соответствующей макету. По желанию можно сделать «Было» и «Стало» кнопками переключения фотографий кота.

"Реализовывать слайдер" это значит сделать так, чтобы при перетаскивании ручки изменялась видимость котов. Но это не значит, что можно взять, да и поставить вместо части интерфейса картинку.
Там верстка в любом случае должна быть готовой для того, чтобы к ней подключили JS и сделали границу передвигаемой. Это будет выглядеть как-то так:

```html
<div class="cat-range">
  <div class="cat-range__img" style="width: 50%;">
    <img src="..." alt="Толстый кот">
  </div>
  <div class="cat-range__img">
    <img src="..." alt="Тощий кот">
  </div>
</div>
```

2021-05-24 21:28 UTC, wrgraff approved these changes

2021-05-24 21:28 UTC, merged